
# Name your project! Project names should contain only lowercase characters
# and underscores. A good package name should reflect your organization's
# name or the intended use of these models
name: 'nwsfl_dbt'
version: '1.0.0'

# This setting configures which "profile" dbt uses for this project.
profile: 'nwsfl_dbt'

# These configurations specify where dbt should look for different types of files.
# The `model-paths` config, for example, states that models in this project can be
# found in the "models/" directory. You probably won't need to change these!
model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

clean-targets:         # directories to be removed by `dbt clean`
  - "target"
  - "dbt_packages"


# Configuring models
# Full documentation: https://docs.getdbt.com/docs/configuring-models

# Model configurations follow dbt best practices:
# - Staging models are views (lightweight, build quickly)
# - Intermediate models are ephemeral (exist only during build)
# - Marts models are tables (optimized for querying)
models:
  nwsfl_dbt:
    # Staging layer - raw data transformations
    staging:
      +materialized: view
      +schema: staging
      
    # Intermediate layer - business logic transformations  
    intermediate:
      +materialized: ephemeral
      +schema: intermediate
      
    # Marts layer - final analytics-ready models
    marts:
      +materialized: table
      +schema: marts
      
    # Example models (can be deleted after setup)
    example:
      +materialized: view
