match_report_ids:
    table_columns:
        - id
        - player_id
        - match_id
        - team_id
        - position
        - nation
        - shirtnumber
        - age
        - minutes
    primary_key: id
    staging_table_name: 'soccer.stg_dm_match_report_ids'
    table_name: 'soccer.dm_match_report_ids'
    file_path: 'upload_data/match_reports/summary'
    project_id: 'sportsreference-405418'
player_match_summary:
    table_columns:
        - id
        - goals
        - pk_goals
        - pk_attempts
        - shots
        - shots_on_target
        - yellow_cards
        - red_cards
        - touches
        - tackles
        - interceptions
        - blocks
        - xg
        - npxg
        - xag
        - shot_creating_actions
        - goal_creating_actions
        - passes_completed
        - passes_attempted
        - progressive_passes
        - carries
        - progressive_carries
        - take_ons_attempted
        - take_ons_succeeded
    primary_key: id
    staging_table_name: 'soccer.stg_f_player_match_summary'
    table_name: 'soccer.f_player_match_summary'
    file_path: 'data/match_reports/summary'
    project_id: 'sportsreference-405418'
player_match_possession:
    table_columns:
        - id
        - touches
        - touches_def_penalty_area
        - touches_def_third
        - touches_mid_third
        - touches_att_third
        - touches_att_penalty_area
        - touches_live
        - take_ons_attempted
        - take_ons_succeeded
        - take_ons_tackled
        - carries
        - progressive_carries
        - carries_into_final_third
        - carries_into_penalty_area
        - carries_miscontrolled
        - carries_disposessed
        - passes_recieved
        - progressive_passes_recieved
    primary_key: id
    staging_table_name: 'soccer.stg_f_player_match_possession'
    table_name: 'soccer.f_player_match_possession'
    file_path: 'upload_data/match_reports/possession'
    project_id: 'sportsreference-405418'
player_match_defense:
    table_columns:
        - id
        - tackles_att
        - tackles_won
        - tackles_def_third
        - tackles_mid_third
        - challenges_won
        - challenges_att
        - challenges_lost
        - blocks
        - shot_blocks
        - pass_blocks
        - interceptions
        - clearances
        - errors_lead_to_shot
    primary_key: id
    staging_table_name: 'soccer.stg_f_player_match_defense'
    table_name: 'soccer.f_player_match_defense'
    file_path: 'upload_data/match_reports/defense'
    project_id: 'sportsreference-405418'
player_match_passing:
    table_columns:
        - id
        - passes_completed
        - passes_attempted
        - total_pass_distance
        - total_progressive_pass_distance
        - short_passes_completed
        - short_passes_attempted
        - medium_passes_completed
        - medium_passes_attempted
        - long_passes_completed
        - long_passes_attempted
        - assists
        - xag
        - xa
        - key_passes
        - passes_into_final_third
        - passes_into_penalty_area
        - crosses_into_penalty_area
        - progressive_passes
    primary_key: id
    staging_table_name: 'soccer.stg_f_player_match_passing'
    table_name: 'soccer.f_player_match_passing'
    file_path: 'upload_data/match_reports/passing'
    project_id: 'sportsreference-405418'
player_match_passing_types:
    table_columns:
        - id
        - passes_attempted
        - passes_live
        - passes_dead_ball
        - passes_free_kick
        - passes_through_balls
        - passes_switches
        - pass_types_crs
        - passes_throw_ins
        - passes_corner_kicks
        - corner_kicks_inswinging
        - corner_kicks_outswinging
        - corner_kicks_straight
        - passes_completed
        - passes_offside
        - passes_blocked
    primary_key: id
    staging_table_name: 'soccer.stg_f_player_match_passing_types'
    table_name: 'soccer.f_player_match_passing_types'
    file_path: 'upload_data/match_reports/passing_types'
    project_id: 'sportsreference-405418'
player_match_misc:
    table_columns:
        - id
        - yellow_cards
        - red_cards
        - second_yellow_cards
        - fouls
        - fouled
        - offsides
        - crosses
        - interceptions
        - tackles_won
        - pks_won
        - pks_converted
        - own_goals
        - ball_recoveries
        - aerial_duels_won
        - aerial_duels_lost
    primary_key: id
    staging_table_name: 'soccer.stg_f_player_match_misc'
    table_name: 'soccer.f_player_match_misc'
    file_path: 'upload_data/match_reports/misc'
    project_id: 'sportsreference-405418'
