defense_agg_cols:
    - tackles_att
    - tackles_won
    - tackles_def_third
    - tackles_mid_third
    - tackles_att_third
    - challenges_won
    - challenges_lost
    - challenges_att
    - blocks
    - shot_blocks
    - pass_blocks
    - interceptions
    - clearances
    - errors_lead_to_shot
possession_agg_cols:
    - touches
    - touches_def_penalty_area
    - touches_def_third
    - touches_mid_third
    - touches_att_third
    - touches_att_penalty_area
    - take_ons_tackled
    - total_carries_distance
    - total_progressive_carries_distance
    - carries_into_final_third
    - carries_into_penalty_area
    - carries_miscontrolled
    - carries_disposessed
    - passes_received
    - progressive_passes_received
passing_agg_cols:
    - passes_completed
    - passes_attempted
    - total_pass_distance
    - total_progressive_pass_distance
    - short_passes_completed
    - short_passes_attempted
    - medium_passes_completed
    - medium_passes_attempted
    - long_passes_completed
    - long_passes_attempted
    - assists
    - xag
    - xa
    - key_passes
    - passes_into_final_third
    - crosses_into_penalty_area
    - progressive_passes
passing_types_agg_cols:
    - passes_attempted
    - passes_completed
    - passes_live
    - passes_dead_ball
    - passes_free_kick
    - passes_through_balls
    - passes_corner_kicks
    - corner_kicks_inswinging
    - corner_kicks_outswinging
    - corner_kicks_straight
    - passes_offside
    - passes_blocked
summary_agg_cols:
    - goals
    - assists
    - pk_goals
    - pk_attempts
    - shots
    - shots_on_target
    - yellow_cards
    - red_cards
    - touches
    - interceptions
    - blocks
    - xg
    - npxg
    - xag
    - shot_creating_actions
    - goal_creating_actions
    - passes_completed
    - passes_attempted
    - progressive_passes
    - carries
    - progressive_carries
    - take_ons_attempted
    - take_ons_succeeded
summary_cluster_cols:
    - goals
    - assists
    - shots
    - pct_shots_on_target
    - yellow_cards
    - touches
    - interceptions
    - blocks
    - npxg
    - xag
    - shot_creating_actions
    - goal_creating_actions
    - take_ons_attempted
    - take_on_pct
passing_cluster_cols:
    - passes_completed
    - pass_pct
    - distance_per_pass
    - progressive_distance_per_progressive_pass
    - short_passes_completed
    - short_passing_pct
    - medium_passes_completed
    - medium_passing_pct
    - long_passes_completed
    - long_passing_pct
    - xag
    - xa
    - key_passes
    - passes_into_final_third
    - crosses_into_penalty_area
possession_cluster_cols:
    - touches
    - pct_touches_def_penalty_area
    - pct_touches_def_third
    - pct_touches_mid_third
    - pct_touches_att_third
    - pct_touches_att_penalty_area
    - take_ons_tackled
    - total_carries_distance
    - total_progressive_carries_distance
    - carries_into_final_third
    - carries_into_penalty_area
    - carries_miscontrolled
    - carries_disposessed
    - passes_recieved
    - progressive_passes_recieved
defense_cluster_cols:
    - tackles_att
    - tackles_won_pct
    - pct_tackles_def_third
    - pct_tackles_mid_third
    - pct_tackles_att_third
    - challenges_att
    - challenges_won_pct
    - shot_blocks
    - pass_blocks
    - interceptions
    - clearances
    - errors_lead_to_shot
passing_types_cluster_cols:
    - pct_passes_live
    - pct_passes_dead_ball
    - passes_free_kick
    - passes_through_balls
    - passes_corner_kicks
    - passes_offside
    - passes_blocked