match_report_path:
    0: raw_data/{}/home_team_{}.pkl
    1: raw_data/{}/away_team_{}.pkl
    2: raw_data/{}/{}_match_stats.pkl
    3: raw_data/{}/home_team_summary_{}.pkl
    4: raw_data/{}/home_team_passing_{}.pkl
    5: raw_data/{}/home_team_passing_types_{}.pkl
    6: raw_data/{}/home_team_defense_{}.pkl
    7: raw_data/{}/home_team_possession_{}.pkl
    8: raw_data/{}/home_team_misc_{}.pkl
    9: raw_data/{}/home_team_keeper_{}.pkl
    10: raw_data/{}/away_team_summary_{}.pkl
    11: raw_data/{}/away_team_passing_{}.pkl
    12: raw_data/{}/away_team_passing_types_{}.pkl
    13: raw_data/{}/away_team_defense_{}.pkl
    14: raw_data/{}/away_team_possession_{}.pkl
    15: raw_data/{}/away_team_misc_{}.pkl
    16: raw_data/{}/away_team_keeper_{}.pkl
    17: raw_data/{}/all_shots_{}.pkl
match_report_folder:
    0: lineups
    1: lineups
    2: match_summary
    3: match_reports/summary
    4: match_reports/passing
    5: match_reports/passing_types
    6: match_reports/defense
    7: match_reports/possession
    8: match_reports/misc
    9: match_reports/keeper
    10: match_reports/summary
    11: match_reports/passing
    12: match_reports/passing_types
    13: match_reports/defense
    14: match_reports/possession
    15: match_reports/misc
    16: match_reports/keeper
    17: shots