version: 2

sources:
  - name: nwsfl
    description: NWSFL fantasy league source data
    schema: nwsfl
    tables:
      # Dimension tables
      - name: dim_competitions
        description: Soccer competition/league information
        columns:
          - name: id
            description: Primary key - competition identifier
            tests:
              - unique
              - not_null
              
      - name: dim_players
        description: Player master data
        columns:
          - name: id
            description: Primary key - player identifier
            tests:
              - unique
              - not_null
          - name: player_id
            description: Player ID from source system
          - name: player_name
            description: Player name
            
      - name: dim_matches
        description: Match/game information
        columns:
          - name: id
            description: Primary key - match identifier
            tests:
              - unique
              - not_null
          - name: match_date
            description: Date of the match
          - name: home_team_id
            description: Home team identifier
          - name: away_team_id
            description: Away team identifier
            
      - name: dim_squads
        description: Team/squad information
        columns:
          - name: id
            description: Primary key - squad identifier
            tests:
              - unique
              - not_null
              
      # Fact tables
      - name: f_player_match_summary
        description: Player match performance summary statistics
        
      - name: f_player_match_passing
        description: Player passing statistics by match
        
      - name: f_player_match_defense
        description: Player defensive statistics by match
        
      - name: f_player_match_possession
        description: Player possession statistics by match
        
      - name: f_shots
        description: Individual shot data
        
      # Fantasy league tables
      - name: fantasy_players_test
        description: Fantasy player mappings
        
      - name: fantasy_teams
        description: Fantasy league teams
        columns:
          - name: team_id
            tests:
              - unique
              - not_null
              
      - name: fantasy_rosters
        description: Fantasy team rosters
        
      - name: fantasy_team_points
        description: Fantasy team scoring by matchweek

