name: 'dbt_fotmob'
version: '1.0.0'
config-version: 2

profile: 'dbt_fotmob'

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

clean-targets:
  - "target"
  - "dbt_packages"

seeds:
  dbt_fotmob:
    fantasy_weekly_benches_2026:
      +column_types:
        week: integer
        manager: varchar
        benched_player: varchar
    fantasy_weeks_2026:
      +column_types:
        week: integer
        week_start: date
        week_end: date

models:
  dbt_fotmob:
    +materialized: view

quoting:
  database: true
