CREATE TABLE f_player_match_summary(
    id varchar(40) primary key,
    player_id varchar(20),
    team_id varchar(20),
    match_id varchar(20),
    minutes int,
    goals int,
    assists int,
    pk_goals int,
    pk_attempts int,
    shots int,
    shots_on_target int,
    yellow_cards int, 
    red_cards int,
    touches int, 
    tackles int, 
    interceptions int,
    blocks int,
    xg float,
    npxg float,
    xag float,
    shot_creating_actions int,
    goal_creating_actions int
);